### ISSUE TITLE
"Try nr." Loop

### ISSUE THREAD

**Issue by nferdazel** [itsthooor/passgen#1]
Hey! I was exploring Reddit met your post about this tool. So I created my venv to run your software. Unfortunately, after some tries with various configurations, the tool is somewhat looping the `Try nr.`. I was generating 40 chars with Normal + Safemode combo, and then the `Try nr.` going wild in my terminal until I press Ctrl + C manually. The tries are ended up in `Try nr.: 8725094`. My point is, are your tool tests it's own result of password? I don't know what `Try nr.` purposes.

**Comment by cheese-wheel-sh** [comment]
Try nr. means the tries of safemode it goes through the while loops.
I used it as print() to always have an actual number, because the program "freezes" while it is making a password and so i don't see the number of tries in the actual GUI. That is a big number and also: Which version are you using right now?
Maybe version 0.4 could help with that.

**Comment by nferdazel** [comment]
Ah, I see it. well done, mate.

> Which version are you using right now?

I'm pretty sure cloning the 0.3 a moment ago. I'll try the 0.4
